name: Build App

on:
  push:
    tags:
      - 'v*'  # Only build when a version tag is pushed (e.g., v1.0.0)
  workflow_dispatch:  # Also allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if exist requirements.txt pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile main.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: app-executable
          path: dist/main.exe
