name: Build Windows Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Using 3.10 for better pygame compatibility

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller cython pygame==2.5.2  # Slightly older stable version

    - name: Build the Cython extension
      run: |
        python setup.py build_ext --inplace
        dir

    - name: Run PyInstaller
      run: |
        $pyinstallerArgs = @(
          "--onefile",
          "--add-data", "bomb_game.pyd;.",
          "--hidden-import", "pygame",
          "--collect-all", "bomb_game",
          "main.py"
        )
        pyinstaller @pyinstallerArgs

    - name: Verify the build (silent mode)
      run: |
        cd dist
        # Disable audio for the test run
        $env:SDL_AUDIODRIVER = "dummy"
        .\main.exe --no-sound || echo "Test run completed (audio not available in CI)"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: beat-the-bomb-app
        path: dist/
