name: Build App

on:
  push:
    tags:
      - 'v*'  # Run on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") { pip install -r requirements.txt }

      - name: Build with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile --hidden-import=bomb_game main.py
          pyinstaller --onefile main.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: app-executable
          path: dist/main.exe
