name: Build Windows Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Recommend using 3.10 instead of 3.13 for better compatibility

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller cython pygame

    - name: Build the Cython extension
      run: |
        python setup.py build_ext --inplace
        dir  # Verify bomb_game.pyd exists

    - name: Run PyInstaller
      run: |
        pyinstaller --onefile ^
          --add-data "bomb_game.pyd;." ^
          --hidden-import=pygame ^
          --collect-all bomb_game ^
          main.py

    - name: Verify the build
      run: |
        cd dist
        .\main.exe --version || echo "Test run failed but continuing"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: beat-the-bomb-app
        path: dist/
