name: Build Windows Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller cython pygame==2.5.2

    - name: Build the Cython extension
      run: |
        python setup.py build_ext --inplace
        dir

    - name: Run PyInstaller
      run: |
        $pyinstallerArgs = @(
          "--onefile",
          "--add-data", "bomb_game.pyd;.",
          "--add-data", "questions.json;.",  # Add this line
          "--add-data", "explosion.wav",  # Add if you have other assets
          "--hidden-import", "pygame",
          "--collect-all", "bomb_game",
          "main.py"
        )
        pyinstaller @pyinstallerArgs

    - name: Verify build (basic check)
      run: |
        cd dist
        if (Test-Path .\main.exe) {
          echo "Build verification passed - executable exists"
        } else {
          echo "Build verification failed"
          exit 1
        }

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: beat-the-bomb-app
        path: dist/
